import './globals.css'
import {Mulish} from 'next/font/google'

const mulish = Mulish({
    weight: ['300', '400', '500', '600', '700', '800', '900'],
    subsets: ['latin'],
    display: 'swap',
})

import Header from "@/app/components/Header";


export const metadata = {
    title: 'YFlix',
    description: 'Generated by Abdul Mateen',
}

export default function RootLayout({children}) {
    return (
        <html lang="en" className={mulish.className}>
        <body>
        <Header/>
        {children}
        </body>
        </html>
    )
}
